services:
  client.administrators:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:8001;http://+:8000"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Client.Administrators.pfx"
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - ./certs/.aspnet/https/Client.Administrators.pfx:/home/app/.aspnet/https/Client.Administrators.pfx:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - images-volume:/uploads/images