services:
  client.administrators:
    image: ${DOCKER_REGISTRY-}client.administrators
    build:
      context: .
      dockerfile: src/Client.Administrators.Presentation/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      shopeefood-clone-net:
    
  sync-images:
    image: alpine
    depends_on:
      - client.administrators
    volumes:
      - images-volume:/uploads/images
      - D:/Internship/Code/Demo/ShopeeFood_Clone/images:/host-images
      - ./sync-images.sh:/sync-images.sh
    command: sh /sync-images.sh
        
volumes:
  images-volume:
    external: true

networks:
  shopeefood-clone-net:
    external: true
